_target_: src.model.embedder.EmbedderMarkerPriorInjectionBin
name: mark_emb_skip_prior_injection_bin
dim_hid: 64
dim_out: ${encoder.d_model}
emb_depth: 4
pos_emb_init: True
use_skipcon_mlp: True
num_bins: ${dataset.num_bins}