_target_: src.model.target_head.MixtureGaussian
name: mixture_gaussian
dim_y: 1
d_model: ${encoder.d_model}
dim_feedforward: 128
num_components: 20
single_head: False
trange: ${dataset.x_range}
std_min: 0.001
loss_latent_weight: ${dataset.loss_latent_weight}
discrete_index: ${dataset.discrete_index}
loss_data_weight: ${dataset.loss_data_weight}
