_target_: src.dataset.sampler_sbi_prior.Sampler
name : "gaussian_pi_bin"
dim_input: 2
dim_output: 1
bias_init: false
dim_tar: 1
num_ctx: 'random'
x_range: [-2, 2]
num_latent: 2
num_bins: 100
device: 'cpu'

ctx_tar_sampler: 'onesidesampler'
n_total_points: 20 # not needed
min_num_points: 10
max_num_points: 20

loss_latent_weight: 1
loss_data_weight: 1

discrete_index: null

problem:
  _target_: src.dataset.sbi.gaussian.Gaussian
