_target_: src.dataset.sampler_twoway.Sampler
name : "lengthscale_gp2d_2way_fast"
num_ctx: 'random'
dim_input: 2 # 1 marker + 1 actual input dim
num_latent: 2 # lengthscale_x1,  sigma_f
max_ctx_points: 50
min_ctx_points: 3
n_total_points: 200 # at least num_latent + max_ctx_points
x_range: [[-1],[1]]
device: 'cpu'
ctx_tar_sampler: 'bernuniformsampler'
problem:
  _target_: src.dataset.latents.hyperparam_gpnd_2way.GPND2WayManyKernelsFast
  kernel_list: ["matern12","matern32","matern52","rbf"]
  kernel_sample_weight: [0.1, 0.2, 0.35, 0.35]
  lengthscale_range: [0.05, 2] # for nd case lengthscales will be multiplied by sqrt(actual_input_dim)
  std_range: [0.1, 2]
  p_iso: 0.5