_target_: src.dataset.sampler_twoway.Sampler
name : "sir"
num_ctx: 'random'
min_num_points: 5
max_num_points: 10

num_latent: 2

dim_input: 2
dim_tar: 1  # not used

n_total_points: 10 # not needed
x_range: [0, 1]
device: 'cuda'
ctx_tar_sampler: 'bernuniformsampler'
discrete_index: null

loss_latent_weight: 1
loss_data_weight: 1

problem:
  _target_: src.dataset.sbi.sir.SIR
  x_file: 'data/x_sir_10000.pt'
  theta_file: 'data/theta_sir_10000.pt'
  batch_size: ${batch_size}
  shuffle: True
  order: 'random'