_target_: src.dataset.sampler_sbi_prior.Sampler
name : "turin_pi"
dim_input: 2
dim_output: 1
bias_init: false
dim_tar: 1
num_ctx: 'random'
x_range: [0, 1]
num_latent: 4
num_bins: 100
device: 'cpu'

ctx_tar_sampler: 'onesidesampler'
n_total_points: 101 # not needed
min_ctx_points: 50
max_ctx_points: 101

loss_latent_weight: 1
loss_data_weight: 1

discrete_index: null

problem:
  _target_: src.dataset.sbi.turin.TurinPriorInjection
  x_file: 'data/x_turin_pi_10000.pt'
  theta_file: 'data/theta_turin_pi_10000.pt'
  weights_file: 'data/weights_turin_pi_10000.pt'
  batch_size: ${batch_size}
