_target_: src.dataset.sampler_twoway.Sampler
name : "turin"
num_ctx: 'random'
min_ctx_points: 50
max_ctx_points: 101

num_latent: 4

dim_input: 2
dim_output: 1
bias_init: false
dim_tar: 1

n_total_points: 101 # not needed
x_range: [0, 1]
device: 'cpu'
ctx_tar_sampler: 'bernuniformsampler'
discrete_index: null

loss_latent_weight: 1
loss_data_weight: 1

problem:
  _target_: src.dataset.sbi.turin.Turin
  x_file: 'data/x_turin_10000.pt'
  theta_file: 'data/theta_turin_10000.pt'
  batch_size: ${batch_size}
  shuffle: True
  order: 'random'